#!/usr/bin/env python3
import sys
import os
import subprocess
import argparse

def convert_audio(input_file, output_h, name, rate=44100, channels=2, bpp=2):
    """
    Converts audio to raw PCM and generates a C header.
    bpp 1 = U8, 2 = S16LE, 4 = F32LE
    """
    temp_raw = "temp_audio.raw"
    
    fmt = "s16le"
    if bpp == 1: fmt = "u8"
    elif bpp == 4: fmt = "f32le"

    # Use ffmpeg to convert to raw PCM
    cmd = [
        "ffmpeg", "-y", "-i", input_file,
        "-f", fmt, "-ar", str(rate), "-ac", str(channels),
        temp_raw
    ]
    
    try:
        subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except Exception as e:
        print(f"Error running ffmpeg: {e}")
        return

    with open(temp_raw, "rb") as f:
        data = f.read()

    os.remove(temp_raw)

    with open(output_h, "w") as f:
        f.write(f"// Generated by audio2pcm.py\n")
        f.write(f"#ifndef {name.upper()}_H\n")
        f.write(f"#define {name.upper()}_H\n\n")
        f.write(f"#include <stdint.h>\n\n")
        f.write(f"const uint32_t {name}_rate = {rate};\n")
        f.write(f"const uint32_t {name}_channels = {channels};\n")
        f.write(f"const uint32_t {name}_bpp = {bpp};\n")
        f.write(f"const uint32_t {name}_size = {len(data)};\n\n")
        f.write(f"const uint8_t {name}_data[] = {{\n")
        
        for i in range(0, len(data), 12):
            chunk = data[i:i+12]
            hex_data = ", ".join([f"0x{b:02x}" for b in chunk])
            f.write(f"    {hex_data},\n")
            
        f.write(f"}};\n\n")
        f.write(f"#endif // {name.upper()}_H\n")

    print(f"Done! Saved to {output_h} ({len(data)} bytes)")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert audio to PCM C header")
    parser.add_argument("input", help="Input audio file (mp3, wav, etc)")
    parser.add_argument("output", help="Output .h file")
    parser.add_argument("--name", default="audio_raw", help="Variable name")
    parser.add_argument("--rate", type=int, default=44100, help="Sample rate")
    parser.add_argument("--channels", type=int, default=2, help="Channels")
    parser.add_argument("--bpp", type=int, default=2, help="Bytes per sample (1, 2, 4)")
    
    args = parser.parse_args()
    convert_audio(args.input, args.output, args.name, args.rate, args.channels, args.bpp)
