#!/bin/bash
# img2wasm.sh — Unified image to C header converter for Wagnostic
#
# Converts any image to a C header with raw pixel data in the specified format.
# Output filename: <prefix>.<fmt>.h  (e.g. sprite.rgb565.h)
#
# Usage:
#   ./img2wasm.sh <input_image>              Auto-detect: generates <name>.rgb565.h
#   ./img2wasm.sh <input_image> --rgba       Force 32-bit RGBA  (.rgba.h)
#   ./img2wasm.sh <input_image> --rgb565     Force 16-bit RGB565 (.rgb565.h)
#   ./img2wasm.sh <input_image> --rgb332     Force 8-bit RGB332  (.rgb332.h)
#   ./img2wasm.sh <input_image> -o <prefix>  Custom output prefix (without extension)
#
# Dependencies: ffmpeg, hexdump
#
# Examples:
#   ./img2wasm.sh photo.jpg
#   ./img2wasm.sh sprite.webp --rgba -o assets/sprite
#   ./img2wasm.sh tiles.bmp --rgb332 -o tiles

set -e

# ── Defaults ──────────────────────────────────────────────────────────────────
FMT="rgb565"   # default format
PREFIX=""      # auto-derived from input basename
OUTDIR="."

# ── Parse args ────────────────────────────────────────────────────────────────
INPUT=""
while [ $# -gt 0 ]; do
    case "$1" in
        --rgba)    FMT="rgba"   ;;
        --rgb565)  FMT="rgb565" ;;
        --rgb332)  FMT="rgb332" ;;
        -o)        shift; PREFIX="$1" ;;
        -h|--help)
            sed -n '3,15p' "$0" | sed 's/^#//'
            exit 0
            ;;
        *)
            if [ -z "$INPUT" ]; then
                INPUT="$1"
            else
                echo "Error: unexpected argument: $1" >&2
                exit 1
            fi
            ;;
    esac
    shift
done

if [ -z "$INPUT" ]; then
    echo "Error: missing input image" >&2
    echo "Usage: $0 <input_image> [--rgb565|--rgba|--rgb332] [-o <prefix>]" >&2
    exit 1
fi

if [ ! -f "$INPUT" ]; then
    echo "Error: file not found: $INPUT" >&2
    exit 1
fi

# Derive prefix from input filename if not provided
if [ -z "$PREFIX" ]; then
    BASENAME=$(basename "$INPUT")
    PREFIX="${BASENAME%.*}"
    # Remove any existing format-like suffix (.rgba/.rgb565/.rgb332) from basename
    PREFIX="${PREFIX%.rgba}"
    PREFIX="${PREFIX%.rgb565}"
    PREFIX="${PREFIX%.rgb332}"
fi

# ── Map format to ffmpeg pix_fmt and C type ────────────────────────────────────
case "$FMT" in
    rgba)
        FFMPEG_FMT="rgba"
        C_TYPE="uint32_t"
        HEX_FMT='1/4 "0x%08x, "'
        EXT="rgba"
        ;;
    rgb565)
        FFMPEG_FMT="rgb565le"
        C_TYPE="uint16_t"
        HEX_FMT='1/2 "0x%04x, "'
        EXT="rgb565"
        ;;
    rgb332)
        FFMPEG_FMT="rgb8"
        C_TYPE="uint8_t"
        HEX_FMT='1/1 "0x%02x, "'
        EXT="rgb332"
        ;;
esac

HEADER="${PREFIX}.${EXT}.h"
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

# ── Get dimensions ────────────────────────────────────────────────────────────
W=$(ffprobe -v error -select_streams v:0 -show_entries stream=width  -of default=noprint_wrappers=1:nokey=1 "$INPUT")
H=$(ffprobe -v error -select_streams v:0 -show_entries stream=height -of default=noprint_wrappers=1:nokey=1 "$INPUT")

if [ -z "$W" ] || [ -z "$H" ]; then
    echo "Error: could not determine dimensions of $INPUT" >&2
    exit 1
fi

# ── Convert to raw pixels ─────────────────────────────────────────────────────
ffmpeg -v error -i "$INPUT" -f rawvideo -pix_fmt "$FFMPEG_FMT" -y "$TMP"

RAW_SIZE=$(stat -c%s "$TMP" 2>/dev/null || stat -f%z "$TMP" 2>/dev/null)
echo "--- Converted $INPUT ($W x $H, $FMT, $RAW_SIZE bytes) ---"

# ── Generate header ───────────────────────────────────────────────────────────
GUARD="WASM_${PREFIX}_${EXT}_H"

{
    echo "/* Auto-generated by img2wasm.sh from $INPUT */"
    echo "#ifndef $GUARD"
    echo "#define $GUARD"
    echo "#include <stdint.h>"
    echo ""
    echo "static const int ${PREFIX}_width = $W;"
    echo "static const int ${PREFIX}_height = $H;"
    echo "static const $C_TYPE ${PREFIX}_pixels[] = {"
    hexdump -v -e "$HEX_FMT" "$TMP"
    echo ""
    echo "};"
    echo ""
    echo "#endif /* $GUARD */"
} > "$HEADER"

echo "--- Generated $HEADER ---"
