#!/bin/bash

show_help() {
    echo "Usage: $0 <input_image> [output_prefix] [bpp: 8|16|32]"
    echo "Default BPP is 16."
    echo "Output: <output_prefix>.raw and <output_prefix>_data.h"
    exit 1
}

if [ "$#" -lt 1 ]; then show_help; fi

IN="$1"
PREFIX="${2:-image}"
BPP="${3:-16}"

case $BPP in
    8)  FMT="rgb8";;
    16) FMT="rgb565le";;
    32) FMT="rgba";;
    *)  echo "Invalid BPP: $BPP. Use 8, 16 or 32."; exit 1;;
esac

RAW_OUT="${PREFIX}.raw"
HEADER_OUT="${PREFIX}.h"
VAR_NAME="${PREFIX##*/}"
echo "--- DEBUG: PREFIX=$PREFIX VAR_NAME=$VAR_NAME ---"

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

if [ ! -f "$IN" ]; then echo "Error: $IN not found"; exit 1; fi

# Get dimensions
W=$(ffprobe -v error -select_streams v:0 -show_entries stream=width -of default=noprint_wrappers=1:nokey=1 "$IN")
H=$(ffprobe -v error -select_streams v:0 -show_entries stream=height -of default=noprint_wrappers=1:nokey=1 "$IN")

if [ -z "$W" ] || [ -z "$H" ]; then
    echo "Error: Could not determine dimensions of $IN"
    exit 1
fi

echo "--- Converting image to $FMT ($BPP bpp) ---"
ffmpeg -v error -i "$IN" -f rawvideo -pix_fmt "$FMT" -y "$TMP_DIR/raw.tmp"
if [ ! -f "$TMP_DIR/raw.tmp" ]; then
    echo "Error failed to convert image."
    exit 1
fi

echo "--- Assembling $RAW_OUT ---"
cat "$TMP_DIR/raw.tmp" > "$RAW_OUT"

echo "--- Generating $HEADER_OUT ---"
{
    echo "/* Automatically generated by img2fb.sh */"
    echo "#ifndef IMAGE_DATA_H"
    echo "#define IMAGE_DATA_H"
    echo "static const int ${VAR_NAME}_width = $W;"
    echo "static const int ${VAR_NAME}_height = $H;"
    
    if [ "$BPP" -eq 16 ]; then
        echo "static const unsigned short ${VAR_NAME}_raw[] = {"
        hexdump -v -e '1/2 "0x%04x, "' "$RAW_OUT"
    elif [ "$BPP" -eq 32 ]; then
        echo "static const unsigned int ${VAR_NAME}_raw[] = {"
        hexdump -v -e '1/4 "0x%08x, "' "$RAW_OUT"
    else
        echo "static const unsigned char ${VAR_NAME}_raw[] = {"
        hexdump -v -e '1/1 "0x%02x, "' "$RAW_OUT"
    fi
    
    echo "};"
    echo "#endif"
} > "$HEADER_OUT"

echo "Done! Generated $RAW_OUT and $HEADER_OUT ($W x $H at $BPP bpp)."
