#!/bin/bash
# img2c.sh — DEPRECATED: use img2wasm.sh instead
#   Old: ./img2c.sh photo.jpg assets/image.h
#   New: ./img2wasm.sh photo.jpg --rgba -o assets/image
#
# Output: a C header defining IMG_W, IMG_H, and img_data[] (unsigned char, RGBA32)
#
# Dependencies: ffmpeg, xxd
#
# Example:
#   ./img2c.sh photo.jpg assets/image.h
#   // Then in C:
#   #include "image.h"
#   uint32_t* pixels = (uint32_t*)img_data;
#   uint32_t color = pixels[y * IMG_W + x];

set -e

IN="${1:?Usage: $0 <input_image> [output_header]}"
OUT="${2:-$(basename "${IN%.*}").h}"

# Get dimensions using ffprobe
W=$(ffprobe -v error -select_streams v:0 -show_entries stream=width  -of default=noprint_wrappers=1:nokey=1 "$IN")
H=$(ffprobe -v error -select_streams v:0 -show_entries stream=height -of default=noprint_wrappers=1:nokey=1 "$IN")

if [ -z "$W" ] || [ -z "$H" ]; then
    echo "Error: Could not get dimensions of $IN"
    exit 1
fi

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

# Convert to raw RGBA32 via ffmpeg
ffmpeg -v error -i "$IN" -f rawvideo -pix_fmt rgba -y "$TMP"

# Convert raw bytes to C array via xxd
HEADER_GUARD="IMAGE_DATA_$(basename "$OUT" .h | tr '[:lower:]' '[:upper:]')_H"

{
    echo "/* Auto-generated by img2c.sh from $IN */"
    echo "#ifndef $HEADER_GUARD"
    echo "#define $HEADER_GUARD"
    echo ""
    echo "#define IMG_W $W"
    echo "#define IMG_H $H"
    echo ""
    echo "static const unsigned char img_data[] = {"
    xxd -i < "$TMP"
    echo "};"
    echo ""
    echo "#endif"
} > "$OUT"

echo "Generated $OUT ($W x $H RGBA32, $(stat -c%s "$TMP") bytes)"
